### ISSUE TITLE
Release with `package_info_plus: ^8.0.0`

### ISSUE THREAD

**Issue by Chralu** [kauemurakami/app_version_update#30]
Hello,

Thanks for that useful package :)

I see you recently upgraded dependencies to use `package_info_plus: ^8.0.0`. 
Do you have other changes planned before the next release ?

For now, I'll point on your latest commit ;)

Thanks for your help.

**Comment by Macacoazul01** [comment]
@kauemurakami we are still having to use another fork because this one depends on `package_info_plus ^6.0.0 `

Are you planning another release?

**Comment by romatallinn** [comment]
@kauemurakami @pom11 yo

**Comment by romatallinn** [comment]
@Macacoazul01 @Chralu not that I recommend this way of doing things, but you can use it as such, until (or if) they release it.

```
app_version_update:
  git:
    url: https://github.com/kauemurakami/app_version_update
    ref: 499047d
```
